feat: added sitemap
italia/design-comuni-pagine-statiche pull request #115
Opened 2023-04-19 08:51 UTC by zetareticoli

Created a sitemap as example for further implamentation.

2023-04-19 13:30 UTC, danielenole requested changes
thanks @zetareticoli, I'd address the following before merging:

- adding breadcrumbs to the page (Home > Mappa del sito)
- using the same style for all list pages - this means, including the forward slash (**/**) and bold style for Notizie, Comunicati, Avvisi, Categoria 1 (under Documenti e dati), Categoria 2 (under Documenti e dati), Categoria 3 (under Documenti e dati), Categoria 1 (under Eventi), Categoria 2 (under Eventi), Categoria 3 (under Eventi)

2023-04-19 13:42 UTC, zetareticoli commented
> * using the same style for all list pages - this means, including the forward slash (**/**) and bold style for Notizie, Comunicati, Avvisi, Categoria 1 (under Documenti e dati), Categoria 2 (under Documenti e dati), Categoria 3 (under Documenti e dati), Categoria 1 (under Eventi), Categoria 2 (under Eventi), Categoria 3 (under Eventi)

I used the slash when there are nested items under a page only, to differentiate their relationship. Does it make sense?

2023-04-19 14:13 UTC, danielenole commented
> I used the slash when there are nested items under a page only, to differentiate their relationship. Does it make sense?

The thing is... also those other pages have (in the site's architecture) nested pages, just not in the sitemap. Under Notizie you find news pages, under Events you find event pages, etc. It's just not sustainable to add these to the sitemap as it would need to be updated frequently, plus there's going to be hundreds of these pages overtime.

So, if we want to signal nested pages in the site architecture, we should include slashes for those too. If we only want to signal nested pages in the sitemap only, then it's fine as it is. Which of these two was your idea?

2023-04-20 07:19 UTC, danielenole approved these changes

2023-04-20 07:22 UTC, merged