Fix/homepage mobile
italia/design-comuni-pagine-statiche pull request #60
Opened 2022-11-09 15:18 UTC by lorycade

2022-11-10 09:37 UTC, zetareticoli requested changes
Ciao @lorycade invece che aggiungere nuove classi dovremmo far funzionare il tutto utilizzando quelle di base di BootstrapItalia. 

Questa modalità operativa infatti aggiunge troppe eccezioni e ridondanza al codice.

Le card presenti nella pagina argomento sono identiche per struttura a quelle in homepage, pertanto non dovrebbero aver bisogno di una classe dedicata.

Il valore di `height:100%` inoltre è superfluo.

La PR non può essere accettata. Il codice deve essere semplificato.

2022-11-10 13:16 UTC, lorycade commented
@zetareticoli  le card in Argomento sono lievemente diverse, ed hanno un parent diverso dalla home, per quello serve la height al 100%, se no verrebbero di altezze diverse. Se dobbiamo modificarle e renderle uguali strutturalmente a quelle della home, va bene, ma servirebbe comunque una classe per modificarne lo stile e non modificare tutte le altre card presenti nelle varie pagine del sito.

2022-11-11 11:42 UTC, zetareticoli commented
> @zetareticoli le card in Argomento sono lievemente diverse, ed hanno un parent diverso dalla home, per quello serve la height al 100%, se no verrebbero di altezze diverse. Se dobbiamo modificarle e renderle uguali strutturalmente a quelle della home, va bene, ma servirebbe comunque una classe per modificarne lo stile e non modificare tutte le altre card presenti nelle varie pagine del sito.

@lorycade qual'è stato quindi l'approccio seguito per la correzione?

2022-11-11 16:00 UTC, zetareticoli requested changes

2022-11-14 08:15 UTC, lorycade commented
> 

@zetareticoli l'approccio è stato prendere le card della homepage, metterle pari pari all'interno della pagina argomento, e togliere/aggiungere solo classi bootstrap per ottenere la corretta visualizzazione

2022-11-14 08:16 UTC, lorycade commented
> > @zetareticoli le card in Argomento sono lievemente diverse, ed hanno un parent diverso dalla home, per quello serve la height al 100%, se no verrebbero di altezze diverse. Se dobbiamo modificarle e renderle uguali strutturalmente a quelle della home, va bene, ma servirebbe comunque una classe per modificarne lo stile e non modificare tutte le altre card presenti nelle varie pagine del sito.
> 
> @lorycade qual'è stato quindi l'approccio seguito per la correzione?


@zetareticoli l'approccio è stato prendere le card della homepage, metterle pari pari all'interno della pagina argomento, e togliere/aggiungere solo classi bootstrap per ottenere la corretta visualizzazione

2022-11-14 11:02 UTC, zetareticoli approved these changes

2022-11-14 14:25 UTC, merged